# Generated by Django 5.1.7 on 2025-03-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='ecommerce/covers/%Y/%m/%d/'),
        ),
    ]
